<?php

namespace AutoJax;

// ***
// do NOT edit this file
// ***

/**
 * @file
 *
 * single entry point for all ajax calls
 *
 * CORS, HTTPS, caching, and security headers
 * handles preflight (OPTIONS) and POST request validation
 * parses json, validates structure and jwt
 * IP throttling for all requests regardless of auth status
 * dispatches to the appropriate service
 * responds with json with refreshed jwt or file download, as indicated
 *
 * session jwt validation pipeline (for all authenticated services):
 *   1. signature valid
 *   2. type === "session" (reset tokens are rejected here)
 *   3. exp not passed
 *   4. autoJaxFetchUserInfo($uid) called -- loaded from autojax/autojax-fetchUserInfo.php
 *   5. iat >= user->lastRevocation (or NULL) -- revocation check
 *   6. user->accountStatus === "active" -- suspension/termination check
 *
 * admin requests flow through the same pipeline as any other authenticated session.
 * admin.php additionally enforces user->isAdmin before executing any action
 *
 * services must implement `function serviceRequest(): void` and declare
 * `global $autoJaxConfig, $autoJaxRequest;` for the values they need. exit via
 * ajaxExit(), exitUnauthorized(), or dieGracefully()
 *
 * PHP Version 8.5
 *
 * @author
 *   Bennett Barouch
 * @copyright
 *   Copyright 2025-2026 Bennett Barouch
 *   SPDX-License-Identifier: Apache-2.0
 */

// if anything about this POST is off, it's very likely an attack since our protocol is very strict
// that strictness is partially to make everything predictable and coding and debugging easier,
// and partly to facilitate attack detection through deviation from expectations

// ajaxPort.php lives at autojax/ajaxApi/ajaxPort.php
// coreDir (autojax/) and parentDir (parent of autojax/) are derived from __DIR__ -- not stored in json
$_coreDir   = realpath(__DIR__ . "/..");
$_parentDir = realpath(__DIR__ . "/../..");

// locate and parse autojax.json
$_autoJaxJsonPath = $_parentDir . "/autojax.json";
if ( ! file_exists($_autoJaxJsonPath)) {
    http_response_code(500);
    exit;
}
require_once __DIR__ . "/../util/readAutoJaxJson.php";
$_cfg = \AutoJax\readAutoJaxJson($_autoJaxJsonPath);
unset($_autoJaxJsonPath);

// load secrets -- secrets file exposes $autoJaxSecrets with db/email/encryption credentials only
require_once $_cfg->secretsFile;

// load remaining source files using __DIR__-relative paths
require_once __DIR__ . "/../util/util.php";
require_once __DIR__ . "/../util/security.php";
require_once __DIR__ . "/../util/db.php";
require_once __DIR__ . "/../autojax-fetchUserInfo.php";
require_once __DIR__ . "/authThrottling.php";
require_once __DIR__ . "/autojax-services.php";
require_once __DIR__ . "/../util/ajaxResponse.php"; // ajaxExit(), exitUnauthorized(), emitContentTypeHeader()

// load the build-stamped environment marker, present in deployed builds only
// build.js writes dist/autojax-buildenv.php: it putenv's DEV_AND_TEST=true for a dev/test
// build and to nothing for a production build, so inDevAndTest() reflects the build mode
// without any per-host environment configuration (shared-host friendly)
$_buildEnvFile = $_coreDir . "/autojax-buildenv.php";
if (file_exists($_buildEnvFile)) {
    require_once $_buildEnvFile;
}
// assemble $autoJaxConfig from json (non-secrets) + secrets file (secrets)
// this is the only place $autoJaxConfig is built. all other files read it as a global
$_inDebugMode  = \AutoJax\inDevAndTest();
$_builtIn      = \AutoJax\autoJaxServiceConfig();
$_date         = date("Y_m_d");
// resolve logDir: absolute paths used as-is. relative paths resolved from parentDir
$_logDir = ($_cfg->logDir !== "" && $_cfg->logDir[0] === "/")
    ? $_cfg->logDir
    : $_parentDir . "/" . $_cfg->logDir;
\AutoJax\makeDirectory($_logDir);
// deny web access to the log directory in case logDir sits inside DOCUMENT_ROOT, and keep the
// directory itself non-world-readable. written once. cheap file_exists guard on later requests
$_logHtaccess = $_logDir . "/.htaccess";
if ( ! file_exists($_logHtaccess)) {
    @file_put_contents(
        $_logHtaccess,
        "Options -Indexes\n" .
        "<IfModule mod_authz_core.c>\n  Require all denied\n</IfModule>\n" .
        "<IfModule !mod_authz_core.c>\n  Deny from all\n</IfModule>\n"
    );
    @chmod($_logHtaccess, 0644);
}
@chmod($_logDir, 0750);
unset($_logHtaccess);
date_default_timezone_set($_cfg->timezone);

// session length is the idle timeout: clamped to 5-480 minutes, silently, with no error. the 5 floor keeps
// the client pre-expiry warning from going negative. the 480 ceiling (eight hours) is only for apps that
// genuinely need all-day idle tolerance -- anything over 20 minutes weakens the idle guard (see README)
$_sessionMinutes = min(480, max(5, (int)$_cfg->jwt->durationInMinutes));
// absolute session lifetime: a hard cap on total session age regardless of activity or keep-alives, enforced
// statelessly from the signed payload (a refresh copies the original sessionStart forward, so a captured token
// cannot be kept alive past it). default 120 minutes (two hours), hard-capped at 480 (eight hours), and never
// below the idle timeout. there is no "disabled" setting -- a session always has a finite maximum life
$_absoluteMax = isset($_cfg->jwt->absoluteMaxInMinutes) ? (int)$_cfg->jwt->absoluteMaxInMinutes : 120;
$_absoluteMax = min(480, max($_sessionMinutes, $_absoluteMax));

// email-confirmation link lifetime, in minutes. clamped 5-30 (silently, like the jwt durations): 5 is long
// enough for a human to find the mail and click, 30 caps how long an unconfirmed pending account lingers and
// holds an email address. this single clamped value drives both the confirmation token's exp and the
// pending-account purge window. default 10 when unconfigured.
$_confirmTtl = isset($_cfg->emailConfirm->ttlInMinutes) ? (int)$_cfg->emailConfirm->ttlInMinutes : 10;
$_confirmTtl = min(30, max(5, $_confirmTtl));

$autoJaxConfig = (object)[
    "autoJaxCoreDir"               => $_coreDir,
    "parentDir"                    => $_parentDir,
    "parentUrl"                    => $_cfg->parentUrl,
    "ajaxUrl"                      => $_cfg->ajaxUrl,
    "passwordResetUrl"             => $_cfg->parentUrl . "/autojax-resetPassword.html",
    "emailConfirmUrl"              => $_cfg->parentUrl . "/autojax-confirmEmail.html",
    "preflightWithNoOrigin"        => $_cfg->preflightWithNoOrigin,
    "loginUrl"                     => $_cfg->loginUrl,
    // opt-in multi-page session. when true, login sets an httpOnly cross-page cookie and session/read
    // exchanges it for a fresh access jwt, so a real navigation can recover the memory-only session.
    // absent or false (the default) is pure-SPA, memory-only, no cookie. see session.php and the design doc
    "crossPageSession"             => ! empty($_cfg->crossPageSession),
    // session concurrency policy. 1 (default) is unlimited concurrent sessions -- the stateless behavior where
    // the single-session slot columns stay NULL and are never consulted. 0 is single-active-session mode: login
    // records the session id's hash on the user row and every request rejects a token whose id does not match,
    // so a newer login displaces the older (last-wins). only 0 and 1 are meaningful. anything other than 0 reads
    // as unlimited. see session.php (slot seed/clear) and the single-session check below
    "concurrentSessions"           => isset($_cfg->concurrentSessions) ? (int)$_cfg->concurrentSessions : 1,
    "proxy"                        => (object)[
        "trusted" => ! empty($_cfg->proxy->trusted),
        "hops"    => isset($_cfg->proxy->hops) ? max(1, (int)$_cfg->proxy->hops) : 1
    ],
    "log"                          => (object)[
        "error"     => "{$_logDir}/autoJaxError_{$_date}.log",
        "authEvent" => "{$_logDir}/autoJaxEvent_{$_date}.log"
    ],
    "db"                           => (object)[
        "host"     => $autoJaxSecrets->dbHost,
        "database" => $autoJaxSecrets->dbName . ($_inDebugMode ? "Test" : ""),
        "user"     => $autoJaxSecrets->dbUser,
        "password" => $autoJaxSecrets->dbPassword
    ],
    "email"                        => (object)[
        "turnOff"     => ! empty($_cfg->emailTurnOff),
        // carry the configured value through untouched -- never inferred. it is validated for an exact "smtp"
        // or "sendmail" just below, so a missing or unrecognized value fails loudly instead of silently
        // defaulting to a transport this host may not be able to use
        "transport"   => $_cfg->emailTransport ?? null,
        "server"      => $autoJaxSecrets->emailServer,
        "user"        => $autoJaxSecrets->emailUser,
        "password"    => $autoJaxSecrets->emailPassword,
        "techSupport" => $_inDebugMode ? $_cfg->emailSupport->test : $_cfg->emailSupport->prod
    ],
    "encryptionKey"                => $autoJaxSecrets->encryptionKey,
    "encryptionKeyOld"             => $autoJaxSecrets->encryptionKeyOld,
    "encKeyLastUpdate"             => $autoJaxSecrets->encKeyLastUpdate,
    "jwt"                          => (object)[
        "durationInMinutes"    => $_sessionMinutes,
        "absoluteMaxInMinutes" => $_absoluteMax,
        "secret"               => $autoJaxSecrets->jwtSecret,
        "secretOld"            => $autoJaxSecrets->jwtSecretOld,
        "secretLastUpdate"     => $autoJaxSecrets->jwtSecretLastUpdate
    ],
    "loginThrottle"                => $_cfg->loginThrottle,
    "passwordReset"                => $_cfg->passwordReset,
    "emailConfirm"                 => (object)[ "ttlInMinutes" => $_confirmTtl ],
    "passwordResetRequestThrottle" => $_cfg->passwordResetRequestThrottle,
    "passwordResetAttemptThrottle" => $_cfg->passwordResetAttemptThrottle,
    "clientLogThrottle"            => (object)[
        "maxIpFails"      => isset($_cfg->clientLogThrottle->maxIpFails)      ? (int)$_cfg->clientLogThrottle->maxIpFails      : 120,
        "windowInMinutes" => isset($_cfg->clientLogThrottle->windowInMinutes) ? (int)$_cfg->clientLogThrottle->windowInMinutes : 15
    ],
    "inDebugMode"                  => $_inDebugMode,
    // the app's own parsed autojax.json (non-secret -- secrets live in autojax-secrets.php), exposed verbatim
    // so a service handler can read its own app-specific config sections. core consumes the keys it knows
    // (jwt, throttles, email, and so on) from the assembled fields above. anything an app adds for itself --
    // for example the example app's "uploads" block (max size, allowed mime types) -- is read here as
    // $autoJaxConfig->app->uploads. this is config the app declared, never secrets, so surfacing it is safe
    "app"                          => $_cfg,
    "ajaxApi"                      => (object)$_builtIn["services"]
];

// emailTransport must be set explicitly to exactly "smtp" or "sendmail" -- it is never inferred. an absent,
// empty, or unrecognized value is a deployment misconfiguration (most often an upgrade whose config predates
// the transport setting), not a cue to silently pick sendmail on a host that may not be able to deliver that
// way. enforced only when mail is actually sent for real: with email turned off, or under an automated test
// run (which spools instead of delivering), the transport is unused, so the requirement is skipped. fail at
// startup and point the operator at mail-probe.sh, which determines and records the value this host can use
if ( ! $autoJaxConfig->email->turnOff && ! inAutomatedTesting() &&
     $autoJaxConfig->email->transport !== "smtp" && $autoJaxConfig->email->transport !== "sendmail") {
    dieGracefully(
        SERVER_ERROR,
        "autojax cannot start: \"emailTransport\" in autojax.json must be set to exactly \"smtp\" or \"sendmail\". " .
        "autojax will not guess a transport. Run mail-probe.sh to determine which this host can deliver with and set " .
        "\"emailTransport\" accordingly, or set \"emailTurnOff\" to true if this deployment sends no mail."
    );
}
// merge app-specific services from autojax.json into ajaxApi
$_appServicesArray = (array)($_cfg->ajaxApi ?? null);
if (empty($_appServicesArray)) {
    // a deployment-time misconfiguration, not a client error. with no app services declared there is nothing to
    // dispatch, so stop here rather than limp on. dieGracefully logs the corrective guidance to the autojax error
    // log and returns a real 500 (the ajaxExit guard makes this safe even though $autoJaxRequest is not built yet)
    dieGracefully(
        SERVER_ERROR,
        "autojax cannot start: the \"ajaxApi\" section of autojax.json defines no services, so no request can be " .
        "dispatched. Declare at least one app service there, then reload. Each service entry needs a \"serviceFile\" " .
        "and its crud permissions -- use the commented template in autojax.json as a guide."
    );
}
$_collisions = array_intersect_key((array)$autoJaxConfig->ajaxApi, $_appServicesArray);
if ( ! empty($_collisions)) {
    $_names = implode(", ", array_keys($_collisions));
    dieGracefully(
        SERVER_ERROR,
        "autojax cannot start: autojax.json redefines built-in autojax service(s): {$_names}. Built-in services may " .
        "not be overridden. Rename or remove these entries from the \"ajaxApi\" section of autojax.json, then reload."
    );
}
foreach ($_appServicesArray as $_name => $_def) {
    normalizeAppService($_name, $_def);
    $autoJaxConfig->ajaxApi->$_name = $_def;
}
unset($_cfg, $_coreDir, $_parentDir, $_logDir, $_buildEnvFile, $autoJaxSecrets, $_inDebugMode, $_builtIn, $_date, $_sessionMinutes, $_absoluteMax, $_confirmTtl, $_appServicesArray, $_collisions, $_name, $_def, $_names);

/**
 * Emit these headers for all responses, no matter the program's later output
 */
header("Strict-Transport-Security: max-age=31536000; includeSubDomains");
header("X-Frame-Options: deny");
header( "Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:;" .
        " object-src 'none'; base-uri 'self'; form-action 'self'");
header("Referrer-Policy: no-referrer");
header("X-Content-Type-Options: nosniff");
header("X-DNS-Prefetch-Control: On");
// this is a small, low-traffic site, with potentially frequent updates, so clobber caching
header("Cache-Control: no-store");
header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");
$now = gmdate("D, d M Y H:i:s");
header("Last-Modified: {$now} GMT"); // must be in GMT, per spec
header("ETag: " . md5($now));
unset($now);

/**
 * Determines if cross-origin requests are allowed for a specific service, subService, and action.
 * An endpoint is cross-origin-allowed if and only if its permission is false (unauthenticated).
 *
 * @param string $service
 * @param string $subService
 * @param string $action
 * @return bool
 */
function isCrossOriginAllowed($service, $subService, $action) {
    global $autoJaxConfig;
    $def = $autoJaxConfig->ajaxApi->$service ?? null;
    if ($def === null) {
        return false;
    }
    if ( ! empty($subService) && isset($def->subService->$subService)) {
        $permission = $def->subService->$subService->$action ?? null;
    }
    else {
        $permission = $def->$action ?? null;
    }
    return $permission === false;
}

/**
 * resolve the client IP for throttling. by default this is REMOTE_ADDR, the address that actually connected.
 * only when a trusted proxy is configured do we read X-Forwarded-For, taking the entry `hops` positions from
 * the right -- each trusted proxy appends the address it saw, so the real client sits to the right of any
 * client-forged entries. forwarded headers are ignored entirely unless proxy.trusted is set.
 *
 * @return string client IP address
 */
function resolveClientIp() {
    global $autoJaxConfig;
    $remote = $_SERVER["REMOTE_ADDR"] ?? "";
    if (empty($autoJaxConfig->proxy->trusted)) {
        return $remote;
    }
    $forwarded = $_SERVER["HTTP_X_FORWARDED_FOR"] ?? "";
    if ($forwarded === "") {
        return $remote;
    }
    $parts = array_values(array_filter(array_map("trim", explode(",", $forwarded)), "strlen"));
    $idx   = count($parts) - max(1, (int)$autoJaxConfig->proxy->hops);
    return ($idx >= 0 && isset($parts[$idx])) ? $parts[$idx] : $remote;
}
$clientIpAddress = resolveClientIp(); // REMOTE_ADDR, or the real client from X-Forwarded-For behind a trusted proxy

/**
 * determine whether the request arrived over HTTPS. behind a trusted proxy the original scheme is read from
 * X-Forwarded-Proto (the leftmost value). otherwise the direct TLS state in $_SERVER["HTTPS"] is used.
 *
 * use requestIsHttps() (not raw $_SERVER["HTTPS"]) so the scheme matches the browser's Origin even behind a
 * TLS-terminating trusted proxy, where the direct connection is plaintext but X-Forwarded-Proto says https
 *
 * @return bool true if the request is HTTPS
 */
function requestIsHttps() {
    global $autoJaxConfig;
    if ( ! empty($autoJaxConfig->proxy->trusted) && isset($_SERVER["HTTP_X_FORWARDED_PROTO"])) {
        $proto = strtolower(trim(explode(",", $_SERVER["HTTP_X_FORWARDED_PROTO"])[0]));
        return $proto === "https";
    }
    return ! (empty($_SERVER["HTTPS"]) || $_SERVER["HTTPS"] === "off");
}
$scheme = requestIsHttps() ? "https" : "http";

// HSTS only protects a returning browser.
// this will also reject an initial request that is http-not-s (but we allow plain http if not in production)
if (inProd() && $scheme !== "https") {
    writeLog("authEvent", "rejected plaintext (non-HTTPS) request from {$clientIpAddress}");
    header_remove("Content-Type");
    header("Content-Length: 0");
    http_response_code(UPGRADE_REQUIRED);
    exit;
}

$host   = $_SERVER["HTTP_HOST"] ?? "";
// if origin is not set, or set to null, or set to "null", set it to "", else to its actual value
$origin = $_SERVER["HTTP_ORIGIN"] ?? "";
if ($origin === "null") {
    $origin = "";
}
$sameOrigin = ($origin !== "" && $host !== "" && $origin === "{$scheme}://{$host}");
// only emit CORS headers when an origin header is present
// if Origin is missing, it's not a browser CORS request, so don't emit Allow-Origin
unset($scheme, $host);

$requestMethod   = strtoupper($_SERVER["REQUEST_METHOD"] ?? "");

if ($requestMethod === "OPTIONS") { // ajax preflight support
    if ($origin === "") {
        // no origin on a preflight is suspicious – browsers send origin on preflight
        if (empty($autoJaxConfig->preflightWithNoOrigin)) { // not defined or false
            recordIpAddress($clientIpAddress);
            dieGracefully(__attack__, "CORS preflight (OPTIONS) must provide HTTP_ORIGIN");
        }
    }
    else {
        parse_str($_SERVER["QUERY_STRING"] ?? "", $query);
        $service    = $query["service"]    ?? "unknown-service";
        $subService = $query["subService"] ?? "unknown-sub-service";
        $action     = $query["action"]     ?? "unknown-action";
        if ( ! $sameOrigin && ! isCrossOriginAllowed($service, $subService, $action)) {
            recordIpAddress($clientIpAddress);
            dieGracefully(__attack__, "CORS preflight (OPTIONS) denied");
        }
        header("Access-Control-Allow-Origin: {$origin}");
        header("Vary: Origin");
        unset($query, $service, $subService, $action);
    }
    header("Access-Control-Allow-Methods: POST, OPTIONS");
    // our requests carry Content-Type: application/json, which is not a CORS-safelisted value, so a
    // cross-origin browser client's preflight must be told the header is allowed or the request never fires
    header("Access-Control-Allow-Headers: Content-Type");
    header("Access-Control-Max-Age: 14400");
    header_remove("Content-Type");
    header("Content-Length: 0");
    http_response_code(NO_CONTENT);
    exit;
}

if ($requestMethod !== "POST") { // we use POST for 100% of our ajax calls -- if not a POST call, reject it
    $from      = $_SERVER["HTTP_FROM"]       ?? "unknown-host";
    $userAgent = $_SERVER["HTTP_USER_AGENT"] ?? "unknown-agent";
    // let's not make the google bot mad, but end things here either way
    if (preg_match('/.*googlebot.*/i', $from) || preg_match('/.*googlebot.*/i', $userAgent)) {
        header_remove("Content-Type");
        header("Content-Length: 0");
        http_response_code(NO_CONTENT);
        exit;
    }
    // other search engines or any other not-legit API clients hitting our ajax API will fail miserably
    recordIpAddress($clientIpAddress);
    dieGracefully(__attack__, "Attack: Non-POST ajax request :: " . json_encode($_SERVER));
}

// check IP throttle before doing any further work on the request
if (isIpThrottled($clientIpAddress)) {
    writeLog("authEvent", "IP throttled: {$clientIpAddress}");
    ajaxExit(TOO_MANY_REQUESTS, [ "reason" => "too many attempts" ]);
}

$contentType = $_SERVER["CONTENT_TYPE"] ?? "";

$isMultipart = (bool)preg_match('#^\s*multipart/form-data(\s*;|$)#i', $contentType);
$isJson      = (bool)preg_match('#^\s*application/json(\s*;|$)#i',    $contentType);

if ( ! $isMultipart && ! $isJson) {
    recordIpAddress($clientIpAddress);
    dieGracefully(__attack__, "Attack: Unsupported content type requested :: " . json_encode($_SERVER));
}

// check if content too large was triggered
if ($isMultipart) {
    if (empty($_POST) && empty($_FILES) && (int)($_SERVER["CONTENT_LENGTH"] ?? 0) > 0) {
        // not parsed due to malformed multipart or violated post_max_size, assume the latter
        dieGracefully(
            CONTENT_TOO_LARGE, // the client should not have sent something that is too large
            "Multipart body was not parsed - likely exceeds post_max_size (" . ini_get("post_max_size") .
            ") :: " . json_encode($_SERVER)
        );
    }
    // check for partial success
    // did one or more files exceed upload limits (PHP marks each oversize file with an error)
    $oversize = [ ];
    if ( ! empty($_FILES)) {
        foreach ($_FILES as $fieldName => $info) {
            if (is_array($info["error"])) { // multi-file case
                foreach ($info["error"] as $idx => $err) {
                    if ($err === UPLOAD_ERR_INI_SIZE || $err === UPLOAD_ERR_FORM_SIZE) {
                        $oversize[ ] = $info["name"][$idx] ? $info["name"][$idx] : "{$fieldName}[{$idx}]";
                    }
                }
            }
            else { // single-file case
                if ($info["error"] === UPLOAD_ERR_INI_SIZE || $info["error"] === UPLOAD_ERR_FORM_SIZE) {
                    $oversize[ ] = $info["name"] ? $info["name"] : $fieldName;
                }
            }
        }
    }
    if ( ! empty($oversize)) {
        dieGracefully(
            CONTENT_TOO_LARGE, // the client should not have sent something that is too large
            "File(s) exceed upload_max_filesize (" . ini_get("upload_max_filesize") . "): " . implode(", ", $oversize) .
            " :: " . json_encode($_SERVER)
        );
    }
}

// build request

// this will get set to real values once we parse the incoming request completely,
// but we will need to refer to it before then if we encounter early-on error scenarios
// lots of places will use `global $autoJaxRequest;`
$autoJaxRequest = (object)[
    "user"          => null, // populated by autoJaxFetchUserInfo() after JWT verification, null means no auth'd user (yet)
    "autoJaxId"     => 0,    // set by session.php after successful login for ajaxExit JWT issuance, 0 means no auth'd user (yet)
    "service"       => "encountered error before determining requested service",
    "subService"    => "encountered error before determining requested sub-service (if any)",
    "action"        => "encountered error before determining requested action",
    "param"         => null
];


/**
 * Checks configuration to determine whether a given service / sub-service
 * and action requires an authenticated user.
 *
 * The service, sub-service, and action are read from the globals $autoJaxRequest and $autoJaxConfig, so the
 * function takes no parameters. The lookup is performed against $autoJaxConfig->ajaxApi (built in ajaxPort
 * from autojax.json). If the requested combination is undefined or unsupported, execution terminates via
 * dieGracefully() rather than returning.
 *
 * @return bool  True if authentication is required, false if the action is public. Does not return if the
 *               service / sub-service / action combination is not part of the declared api.
 */
function authenticatedUserRequired() {
    global $autoJaxConfig, $autoJaxRequest;
    $service    = $autoJaxRequest->service;
    $subService = $autoJaxRequest->subService ?? null;
    $action     = $autoJaxRequest->action;
    $serviceObj = $autoJaxConfig->ajaxApi->$service ?? null;
    if ( ! $serviceObj) {
        dieGracefully(
            __attack__,
            "Attack: Asking for auth for a non-existent service ({$service}) :: " . json_encode($_SERVER)
        );
    }
    $subServiceObject = null;
    if ($subService                        &&
        isset($serviceObj->subService)     &&
        is_object($serviceObj->subService) &&
        isset($serviceObj->subService->{$subService})
    ) {
        $subServiceObject = $serviceObj->subService->{$subService};
    }
    $serviceName = $subService ? "{$service}->subService->{$subService}" : $service;
    if ($subService && ! $subServiceObject) {
        dieGracefully(
            __attack__,
            "Attack: Auth request for non-existent sub-service {$serviceName} :: " . json_encode($_SERVER)
        );
    }
    $crud = $subServiceObject ? $subServiceObject : $serviceObj;
    if ( ! isset($crud->{$action}) || $crud->{$action} === null) {
        dieGracefully(
            __attack__,
            "Attack: Unsupported action requested {$serviceName}/{$subService}/{$action} :: " . json_encode($_SERVER)
        );
    }
    return $crud->{$action}; // true or false
}

// get the actual request
$uploadedFiles = null;
if ($isMultipart) {
    $json = $_POST["json"] ?? false; // where json shows up in the case of multipart/form-data
    if (is_string($json)) {
        $json = trim($json);
        if ($json === "") {
            $json = false;
        }
    }
    if ( ! is_string($json)) {
        recordIpAddress($clientIpAddress);
        dieGracefully(__attack__, "Attack: Multipart/form-data request missing 'json' counterpart :: " . json_encode($_SERVER));
    }
    if ( ! empty($_FILES)) {
        $uploadedFiles = $_FILES; // populate with uploaded multipart files (if any)
    }
}
else { // json-only, no multipart
    try {
        $json = file_get_contents("php://input"); // where json shows up in the case of application/json
    }
    catch (\Throwable $thr) {
        dieGracefully(
            SERVER_ERROR,
            "Could not read php://input: " .
            $thr->getMessage() . " in " . $thr->getFile() . ":" . $thr->getLine()
        );
    }
    if ( ! $json || trim($json) === "") {
        recordIpAddress($clientIpAddress);
        dieGracefully(__attack__, "Attack: POST input is empty, expected json :: " . json_encode($_SERVER));
    }
}
$post = jsonDecode($json);
if ( ! $post) {
    recordIpAddress($clientIpAddress);
    dieGracefully(__attack__, "Attack: POST input is not valid JSON :: " . json_encode($_SERVER));
}
$jwt                        = $post->jwt        ?? null;
$autoJaxRequest->service    = $post->service    ?? null;
$autoJaxRequest->subService = $post->subService ?? null;
$autoJaxRequest->action     = $post->action     ?? null;
$autoJaxRequest->param      = $post->param      ?? (object)[ ];
if ( ! is_object($autoJaxRequest->param)) {
    recordIpAddress($clientIpAddress);
    dieGracefully(
        __attack__,
        "Attack: If given, ajax request param must be an object, not " . json_encode($post->param) .
        " :: " . json_encode($_SERVER)
    );
}
$autoJaxRequest->param->files = $uploadedFiles;
unset($post);

if ( ! $autoJaxRequest->service || ! $autoJaxRequest->action) {
    recordIpAddress($clientIpAddress);
    dieGracefully(__attack__, "Attack: An ajax request must include service and action :: " . json_encode($_SERVER));
}

// decode and validate the jwt
// all authenticated services flow through this pipeline. admin.php additionally enforces isAdmin = 1.
// clientLog is the one exception -- it is a public, auth-neutral logging sink that must accept a request even
// when the accompanying jwt is missing, stale, or expired (a client reporting an error from a session that
// just ended), so it is never run through session validation here. clientLog.php best-effort decodes the raw
// jwt itself, purely to record uid context in the log line. because it stays unauthenticated, ajaxExit issues
// no refreshed token for it, so there is nothing for the client to echo back on a later call
$autoJaxId = 0;
if ($jwt && $autoJaxRequest->service !== "clientLog") {
    // enforce type === "session" at decode time
    // a reset tokens arriving here indicates an attack (or programming error)
    try {
        $payload = decodeJwtWithOverlap($jwt, true, "session");
    }
    catch (\Throwable $thr) {
        recordIpAddress($clientIpAddress);
        dieGracefully(__attack__, "Attack: Could not decode jwt :: " . json_encode($_SERVER));
    }
    if ($payload === "expired") {
        ajaxExit(__unauthenticated__, [ "reason" => "expired session" ]);
    }
    if ( ! is_object($payload)) {
        recordIpAddress($clientIpAddress);
        dieGracefully(__attack__, "Attack: Invalid jwt payload :: " . json_encode($_SERVER));
    }
    $autoJaxId = $payload->autoJaxId;
    if ($autoJaxId > 0) {
        // carry the original session start forward so refreshes cannot extend a session past its absolute
        // maximum. tokens minted before this field existed fall back to iat (their first-seen time)
        $autoJaxRequest->sessionStart = (isset($payload->sessionStart) && is_int($payload->sessionStart))
            ? $payload->sessionStart
            : $payload->iat;
        // carry the stable per-session id forward onto the request so the refreshed token (minted in ajaxExit)
        // keeps the same id as the token rotates, and so the single-session check below has it. null for any
        // token minted before sessionId existed, which simply fails the match in single-session mode
        $autoJaxRequest->sessionId = (isset($payload->sessionId) && is_string($payload->sessionId))
            ? $payload->sessionId
            : null;
        // absolute session lifetime: a hard cap on total session age, enforced statelessly here. a captured
        // token cannot be kept alive past it because every refresh copies sessionStart unchanged. always set
        // (default 120 min, max 480). exits 401 so the client ends the session and the user re-authenticates
        if (time() - $autoJaxRequest->sessionStart >= $autoJaxConfig->jwt->absoluteMaxInMinutes * 60) {
            writeLog("authEvent", "session past absolute maximum lifetime for uid: {$autoJaxId}");
            ajaxExit(__unauthenticated__, [ "reason" => "session expired" ]);
        }
        // autoJaxFetchUserInfo() fetches user data, calls dieGracefully on any failure
        $autoJaxRequest->user      = \autoJaxFetchUserInfo($autoJaxId);
        $autoJaxRequest->autoJaxId = $autoJaxRequest->user->autoJaxId;
        // revocation check: token was issued before the session was invalidated
        if ($autoJaxRequest->user->lastRevocation !== null && $payload->iat < dbTimestampToEpoch($autoJaxRequest->user->lastRevocation)) {
            writeLog("authEvent", "session token revoked for uid: {$autoJaxId}");
            ajaxExit(__unauthenticated__, [ "reason" => "session revoked" ]);
        }
        // account status check -- a suspended/terminated/pending account must not hold a live session.
        // suspend/terminate already stamp lastRevocation, so the revocation check above normally fires
        // first. these are the defensive backstop for the same-second-issue edge. they exit __unauthenticated__
        // (401), not UNPROCESSABLE (422), so the client treats the session as ended and logs out -- only 401
        // drives endSession() on the client. a mid-session status change must look like session loss, not a
        // recoverable business error the caller is left holding while the dead jwt keeps firing keepAlives
        if ($autoJaxRequest->user->accountStatus === "pending") {
            // a pending account cannot hold a valid session (login refuses it) -- defensive
            writeLog("authEvent", "request by unconfirmed (pending) account uid: {$autoJaxId}");
            ajaxExit(__unauthenticated__, [ "reason" => "account pending confirmation" ]);
        }
        if ($autoJaxRequest->user->accountStatus === "suspended") {
            writeLog("authEvent", "request by suspended account uid: {$autoJaxId}");
            ajaxExit(__unauthenticated__, [ "reason" => "account suspended" ]);
        }
        if ($autoJaxRequest->user->accountStatus === "terminated") {
            writeLog("authEvent", "request by terminated account uid: {$autoJaxId}");
            ajaxExit(__unauthenticated__, [ "reason" => "account not found" ]);
        }
        // single-session enforcement (opt-in: concurrentSessions = 0). login stored the hash of the active
        // session's id on the user row. this request is honored only if its token carries that same id and the
        // slot has not passed its absolute-maximum lifetime. a mismatch means a newer login displaced this
        // session (last-wins) or the feature was just enabled mid-session, so end it like a revocation. the
        // expiry guard can never reject a token the absolute-max check above already let through (slot expiry is
        // sessionStart + absoluteMax), so it only ever frees a stale slot, never false-rejects a live one. in
        // the default unlimited mode the slot is NULL and this whole block is skipped
        if ($autoJaxConfig->concurrentSessions === 0) {
            $slotHash      = $autoJaxRequest->user->currentSessionHash;
            $slotExpiry    = $autoJaxRequest->user->currentSessionExpiration;
            $presentedHash = $autoJaxRequest->sessionId !== null ? hashToken($autoJaxRequest->sessionId) : null;
            $sessionActive = $slotHash !== null
                && $presentedHash !== null
                && hash_equals($slotHash, $presentedHash)
                && $slotExpiry !== null
                && time() < dbTimestampToEpoch($slotExpiry);
            if ( ! $sessionActive) {
                writeLog("authEvent", "single-session: superseded or unknown session for uid: {$autoJaxId}");
                ajaxExit(__unauthenticated__, [ "reason" => "session superseded" ]);
            }
        }
    }
}
if ( ! $autoJaxId) { // we do not have an authenticated user
    if ( ! $sameOrigin && ! isCrossOriginAllowed($autoJaxRequest->service, $autoJaxRequest->subService ?? "", $autoJaxRequest->action)) {
        recordIpAddress($clientIpAddress);
        dieGracefully(__attack__, "Cross-origin POST requests not allowed");
    }
}

if ( ! isset($autoJaxConfig->ajaxApi->{$autoJaxRequest->service})) {
    recordIpAddress($clientIpAddress);
    dieGracefully(__attack__, "Attack: Request for unrecognized service: {$autoJaxRequest->service} :: " . json_encode($_SERVER));
}
// do we have an unauth'd user asking for a service that requires auth
if ( ! $autoJaxId && authenticatedUserRequired()) {
    // a legit client should never request a service for an unauth'd user if it requires auth, so assume this is an attack
    recordIpAddress($clientIpAddress);
    dieGracefully(
        __attack__,
        "Attack: Secure service ({$autoJaxRequest->service}) requested for an unauthenticated use :: " . json_encode($_SERVER)
    );
} // else we have an unauthenticated user asking for a public service that does not require authentication, such as login

// universal per-IP volume cap for unauthenticated public endpoints (login, password, registerNewUser).
// this is the single place generic public throttling lives -- individual services layer only their
// specialized throttles (login-name, password-reset) on top. authenticated traffic is exempt: it already
// carries a validated session. spoofable, so the real amplification defense is the global email cap in
// reportError. this bounds per-source request volume. clientLog gets its own bucket (THROTTLE_CLIENT_LOG)
// rather than the shared public one, so a burst of client error reports cannot exhaust the cap that gates
// login -- clientLog is always unauthenticated here (it is exempt from the session pipeline above)
if ( ! $autoJaxId) {
    $publicBucket = $autoJaxRequest->service === "clientLog" ? THROTTLE_CLIENT_LOG : THROTTLE_PUBLIC;
    if (isIpThrottled($clientIpAddress, $publicBucket)) {
        ajaxExit(TOO_MANY_REQUESTS, [ "reason" => "too many attempts" ]);
    }
    recordIpAddress($clientIpAddress, $publicBucket);
}

// in case the client needs to log an error when there is no currently auth'd user, the clientErrorLog service does not require
// an auth'd user, but it might be called when there happens to be an auth'd user, in which case we want to process the jwt
if ($autoJaxRequest->service === "clientLog" && $jwt) {
    $autoJaxRequest->jwt = $jwt;
}

unset($sameOrigin, $json, $jwt, $autoJaxId);

// now process the request
// built-in services have no serviceFile -- their path is derived from autoJaxCoreDir
// app-specific services resolve to parentDir + serviceFile (parentDir holds autojax/ and autojax.json)
// an app service that omits serviceFile defaults to "<serviceName>.php" -- applied in normalizeAppService()
// app-specific service files are typically in parentDir or (especially if there are many) parentDir/ajaxApi
$serviceDef   = $autoJaxConfig->ajaxApi->{$autoJaxRequest->service} ?? null;
$isAppService = isset($serviceDef->serviceFile);
$serviceFile  = $isAppService
    ? $autoJaxConfig->parentDir . "/" . $serviceDef->serviceFile                   // app-specific service
    : $autoJaxConfig->autoJaxCoreDir  . "/ajaxApi/{$autoJaxRequest->service}.php"; // built-in (auth-related) service
if ( ! file_exists($serviceFile)) {
    dieGracefully(SERVER_ERROR, "Could not load service :: " . json_encode($autoJaxRequest));
}
require_once $serviceFile;
// dispatch the entry point directly, so a service file needs no global-namespace bridge. built-in services live
// in the AutoJax namespace. an app service is global by default (just function serviceRequest() at file scope),
// which is safe because exactly one service is loaded per request, so its global name cannot collide. an app may
// instead put its handler in a namespace by declaring "namespace" in autojax.json. the namespace comes from the
// server-side service definition, never from client input, so a client cannot steer dispatch to an arbitrary
// function. PHP namespace names are case-insensitive, so a "FileCabinet" namespace matches a "fileCabinet" service
$serviceNamespace = $isAppService ? ($serviceDef->namespace ?? null) : "AutoJax";
$serviceEntry     = $serviceNamespace ? "{$serviceNamespace}\\serviceRequest" : "serviceRequest";
if ( ! function_exists($serviceEntry)) {
    dieGracefully(
        SERVER_ERROR,
        "Service {$autoJaxRequest->service} did not define {$serviceEntry}() :: " . json_encode($autoJaxRequest)
    );
}

// request is fully vetted at the generic level, send it on the to requested service
// for service-specific vetting and response
// each service will exit via ajaxExit(), exitUnauthorized(), or dieGracefully()
try {
    $serviceEntry(); // serviceRequest() is the required entry point for every service
}
catch (\Throwable $thr) {
    dieGracefully(
        SERVER_ERROR,
        "Failed during execution of {$autoJaxRequest->service}: " .
        $thr->getMessage() . " in " . $thr->getFile() . ":" . $thr->getLine() .
        " :: " . json_encode($autoJaxRequest)
    );
}

// ajaxPort execution ends here //

/**
 * apply defaults to an app-specific service definition read from autojax.json
 *
 * a service that omits serviceFile defaults to "<serviceName>.php", resolved against parentDir at dispatch.
 * a service that omits namespace defaults to null, meaning the handler is the global serviceRequest() (the common
 * case, safe because one service loads per request). declaring a "namespace" puts the handler in that namespace,
 * dispatched as "<namespace>\serviceRequest" (PHP namespace names are case-insensitive). both are set in autojax.json.
 * any crud action not stated -- on the service or on any of its subService definitions -- is defined as null, meaning the
 * action is not part of the api. cross-origin eligibility is derived from these crud values, never declared.
 *
 * @param string $name the service name, its key in the ajaxApi section
 * @param object $def  the service definition object, mutated in place
 * @return void
 */
function normalizeAppService($name, $def) {
    if ( ! isset($def->serviceFile)) {
        $def->serviceFile = "{$name}.php";
    }
    if ( ! isset($def->namespace)) {
        $def->namespace = null;
    }
    if ( ! isset($def->subService)) {
        $def->subService = null;
    }
    defaultCrud($def);
    if (is_object($def->subService)) {
        foreach ($def->subService as $sub) {
            defaultCrud($sub);
        }
    }
}

/**
 * ensure every crud action exists on a service or subService definition, defaulting absent ones to null
 *
 * @param object $def a service or subService definition object, mutated in place
 * @return void
 */
function defaultCrud($def) {
    $crud = [
        "create",
        "read",
        "update",
        "delete"
    ];
    foreach ($crud as $action) {
        if ( ! isset($def->{$action})) {
            $def->{$action} = null;
        }
    }
}

// ajaxExit(), exitUnauthorized(), and emitContentTypeHeader() now live in util/ajaxResponse.php
// (required above), so they can be unit-tested in isolation from this procedural entry point.
